version: '3.8'

services:
  postgres:
    container_name: plant_sense
    image: postgres:15
    environment:
      POSTGRES_DB: BD_plant_sense
      POSTGRES_USER: plat
      POSTGRES_PASSWORD: plant123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
